### ISSUE TITLE
docker hub shutdown - use biocontainers instead

### ISSUE THREAD

**Issue by glormph** [lehtiolab/ddamsproteomics#13]
Docker hub will sunset "free organizations" so our lehtiolab/ddamsproteomics container will be removed. This is a small problem for reuse of old pipeline versions, as the container can be easily rebuilt locally. Still, it is probably a good idea to migrate to biocontainers instead, as DSL 2 best practices are multiple containers (one per process) anyway, for reuse.

**Comment by Vad1mo** [comment]
If, for some reason, you want to own and control your container images, we are happy to help you out. We operate a Harbor-based [container registry as a service ](https://container-registry.com/)that has many benefits over most of the other registries out there.

There are also features regarding containerized image distribution, that might be valuable too as well.
